### ISSUE TITLE
the field name of your class is not correct: mListener

### ISSUE THREAD

**Issue by narakai** [yangweigbh/VolleyX#5]
onError java.lang.IllegalStateException: the field name of your class is not correct: mListener

 I have set mListener in my GsonRequest

**Comment by yangweigbh** [comment]
is it obfuscated by proguard?

**Comment by narakai** [comment]
The issue occurs occasionally. I have done some proguard work for volley as below:

-dontwarn  com.android.volley.**
-keep class com.android.volley.** {*;}
-keep class com.android.volley.toolbox.** {*;}
-keep class com.android.volley.Response$* { *; }
-keep class com.android.volley.Request$* { *; }
-keep class com.android.volley.RequestQueue$* { *; }
-keep class com.android.volley.toolbox.HurlStack$* { *; }
-keep class com.android.volley.toolbox.ImageLoader$* { *; }

**Comment by yangweigbh** [comment]
-keepclasseswithmembers class ** {
    private ** mListener;
    private ** mErrorListener;
}
try add above snippet

**Comment by narakai** [comment]
Thanks, will have a try. By the way, the class Interception in your library is never used, is it OK to delete this unused class?

**Comment by yangweigbh** [comment]
the Hack.java use Interception class, if you want to delete the Interception class, remember to delete the reference in Hack.java

**Comment by narakai** [comment]
Thanks.
